services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:Testing1234*@db:5432/horilla
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=horilla.settings
    volumes:
      - ./media:/app/media
      - ./static:/app/static
