services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8001"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:Testing1234*@db:5432/horilla
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=horilla.settings
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: horilla
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Testing1234*
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - horilla-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "horilla"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  horilla-data:
